service: cosmic-trails

provider:
  name: aws
  runtime: python3.8
  region: us-west-2

functions:
  hello:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: hello
          method: get